import { Link } from "react-router";
import { ArrowRight } from "lucide-react";
import { Button } from "@/components/ui/button";

const solutions = [
  {
    vertical: "Clinical Risk Assessment",
    problem:
      "Clinicians lack early, quantitative indicators for neurological decline. Observation-based assessment captures only what is already visible. By the time symptoms are clinically apparent, the window for early intervention has narrowed.",
    system:
      "Neuro-D-Forecast passively captures motor and cognitive biomarkers during routine smartphone use. A Bayesian inference layer generates probabilistic risk trajectories across 30, 90, and 180-day windows. Outputs are expressed as posterior distributions, not binary flags.",
    outcome:
      "Risk stratification before clinical symptom onset. Decision support integrated into existing clinical workflows via HL7 FHIR. Confidence intervals that quantify prediction uncertainty rather than obscuring it.",
    product: "Neuro-D-Forecast",
    productHref: "/products/neuro-d-forecast",
  },
  {
    vertical: "Healthcare Data Infrastructure",
    problem:
      "Healthcare organizations operate across fragmented data systems — multiple EHR vendors, siloed lab and imaging platforms, and patient records distributed across incompatible formats. Clinical intelligence requires a unified view that most organizations cannot construct from their existing architecture.",
    system:
      "EaseCare connects to EHR, laboratory, and imaging systems via FHIR R4 interfaces. Data is normalized to a unified patient model. Risk stratification, care gap analysis, and protocol adherence monitoring are computed against the aggregated record.",
    outcome:
      "A single clinical decision support layer across heterogeneous source systems. Care gaps surfaced at point of care. Protocol adherence tracked longitudinally without manual chart review.",
    product: "EaseCare",
    productHref: "/products",
  },
  {
    vertical: "Enterprise System Migration",
    problem:
      "Legacy data infrastructure accumulates over decades without documentation. SSIS packages, SSRS reports, and warehouse schemas contain undocumented business logic and implicit dependencies. Migration projects stall because the existing system cannot be fully mapped through manual analysis.",
    system:
      "An AI agent parses the full infrastructure: SSIS package XML, report definitions, stored procedure logic, and schema metadata. A directed acyclic graph (DAG) is constructed from source systems to final report outputs. Column-level lineage is extracted, including transformations that are embedded in procedural code.",
    outcome:
      "Complete infrastructure map generated before migration begins. Migration sequencing derived from dependency graph. Target-state architecture designed with zero undocumented dependencies.",
    product: "AI Infrastructure Systems",
    productHref: "/products",
  },
  {
    vertical: "Operational Intelligence",
    problem:
      "Operational data in large organizations is distributed across multiple platforms and generated by systems that were not designed to communicate. Decision-making relies on manually assembled reports that lag the operational state by hours or days.",
    system:
      "Data infrastructure analysis identifies the authoritative sources for each operational metric. Lineage extraction maps the path from raw operational events to summary indicators. A unified data model is designed to consolidate sources into a single query layer.",
    outcome:
      "Operational metrics grounded in verified source data. Report latency reduced from batch-overnight to near-real-time. Data quality issues identified and routed to source ownership.",
    product: "AI Infrastructure Systems",
    productHref: "/products",
  },
];

export function Solutions() {
  return (
    <main className="pt-16">
      <section className="border-b border-border">
        <div className="max-w-6xl mx-auto px-6 py-20">
          <p className="text-xs uppercase tracking-widest text-muted-foreground mb-4">
            Solutions
          </p>
          <h1 className="text-4xl md:text-5xl font-semibold tracking-tight mb-6 max-w-2xl">
            Problems first. Systems second.
          </h1>
          <p className="text-muted-foreground max-w-xl leading-relaxed">
            Each solution starts with a well-defined problem. We do not map
            products to markets. We map systems to the specific conditions that
            make a problem hard to solve.
          </p>
        </div>
      </section>

      {solutions.map((s, idx) => (
        <section key={s.vertical} className="border-b border-border">
          <div className="max-w-6xl mx-auto px-6 py-20">
            <div className="flex items-start justify-between gap-6 mb-12">
              <div>
                <span className="text-xs font-mono text-muted-foreground block mb-2">
                  {String(idx + 1).padStart(2, "0")}
                </span>
                <h2 className="text-2xl font-semibold tracking-tight">{s.vertical}</h2>
              </div>
              <Button asChild variant="outline" size="sm" className="shrink-0 hidden md:flex">
                <Link to={s.productHref}>
                  {s.product} <ArrowRight className="ml-2 size-4" />
                </Link>
              </Button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-px bg-border">
              {[
                { label: "The Problem", body: s.problem },
                { label: "The System", body: s.system },
                { label: "The Outcome", body: s.outcome },
              ].map(({ label, body }) => (
                <div key={label} className="bg-background p-8">
                  <p className="text-xs uppercase tracking-widest text-muted-foreground mb-4">
                    {label}
                  </p>
                  <p className="text-sm text-muted-foreground leading-relaxed">{body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>
      ))}

      <section>
        <div className="max-w-6xl mx-auto px-6 py-20 text-center">
          <p className="text-xs uppercase tracking-widest text-muted-foreground mb-4">
            Not finding your problem?
          </p>
          <h2 className="text-2xl font-semibold tracking-tight mb-4">
            Complex problems rarely fit standard categories.
          </h2>
          <p className="text-muted-foreground mb-8 max-w-lg mx-auto">
            Describe the system you're working with. We'll tell you whether we
            can help and what an engagement would look like.
          </p>
          <Button asChild>
            <Link to="/contact">Describe your problem</Link>
          </Button>
        </div>
      </section>
    </main>
  );
}
